### ISSUE TITLE
Give credit to original authors of part of the code

### ISSUE THREAD

**Issue by ctkdeniz** [h0nde/ja3-proxy#3]
A fair amount of the code comes from this repository: https://github.com/CUCyber/ja3transport/blob/master/transport.go
therefore it would also be appropriate to give credit. However the repository is issued under a MIT license which means you can copy the code freely etc.. But its always good to give credit to the original authors :)

**Comment by h0nde** [comment]
I thought I already had a comment for their repo, guess not. I updated the README.
